export const events = [
  {
    title: "Global Tech Summit 2025",
    image: "/images/event1.png",
    slug: "global-tech-summit-2025",
    location: "San Francisco, CA",
    date: "December 10, 2025",
    time: "9:00 AM PST",
  },
  {
    title: "AI & Machine Learning Conference",
    image: "/images/event2.png",
    slug: "ai-ml-conference",
    location: "New York, NY",
    date: "January 15, 2026",
    time: "10:00 AM EST",
  },
  {
    title: "Web Development Hackathon",
    image: "/images/event3.png",
    slug: "web-dev-hackathon",
    location: "Austin, TX",
    date: "February 20, 2026",
    time: "8:00 AM CST",
  },
  {
    title: "Cloud Native Summit",
    image: "/images/event4.png",
    slug: "cloud-native-summit",
    location: "Seattle, WA",
    date: "March 5, 2026",
    time: "9:30 AM PST",
  },
  {
    title: "Cybersecurity Expo",
    image: "/images/event5.png",
    slug: "cybersecurity-expo",
    location: "Washington, D.C.",
    date: "April 12, 2026",
    time: "9:00 AM EST",
  },
  {
    title: "Mobile App Dev Meetup",
    image: "/images/event6.png",
    slug: "mobile-app-dev-meetup",
    location: "Chicago, IL",
    date: "May 1, 2026",
    time: "6:00 PM CST",
  },
];
